### ISSUE TITLE
Setup gRPC for mTLS encrypted websockets communication with reader devices

### ISSUE THREAD

**Issue by DACC4** [presentium/api#4]
**Description**: Ensure all communication between the device and server is encrypted using SSL/TLS certificates.

**Depends on**: 
- Vault configuration (presentium/infrastructure#11)
- Device: Mutual TLS

**Test case**: All traffic between device and server are encrypted and certificates are checked at connection to ensure they are valid and correspond to the remote host.

**Comment by Lutonite** [comment]
We'll need to use https://github.com/grpc-ecosystem/grpc-spring

Configuring it to use Mutual Certificate Authentication using Vault as a PKI.
In a local environment, we should try to deploy a simplified vault infrastructure via docker and testcontainers.
